const initialState = {
  language: 'ελληνικά',
  υπόβαθροΠρογραμματισμού: 'δυναμικό',
  μορφήΣτοιχείων: 'ημιδιαφανή στοιχεία',
  φέγγοςΟρίων: true,
  φέγγοςΣτοιχείων: false,
  showEventColors: false,
  // φίλτροΚατηγορίαςΧρονολογίου: 'Προγραμματισμός',
  φίλτροΚατάστασηςΓεγονότωνΧρονολογίου: '',
  isLoading: false,
  showAlert: false,
  alertType: '',
  alertText: '',
  showSidebar: false,
  technologies: [],
  totalTechnologies: 0,
  certificate: '',
  settings: false,
  // search: '',
  // searchStatus: 'Όλα',
  // searchType: 'Όλα',
  // sortOptions: ['Νεότερες', 'Παλαιότερες', 'Α -> Ω', 'Ω -> Α'],
  // sort: 'Νεότερες',
};

export default initialState;
