export const έννοιες = [
  { ελληνικά: '', αγγλικά: '', σουηδικά: '' },
  { ελληνικά: 'el', αγγλικά: 'en', σουηδικά: 'swe' },
  { ελληνικά: 'gr', αγγλικά: 'uk', σουηδικά: 'se' },
  { ελληνικά: 'Έργα', αγγλικά: 'Projects', σουηδικά: 'Projekt' },
  {
    ελληνικά: 'Έλλειψη εξουσιοδότησης για  πρόσβαση σε αυτήν τη διαδρομή',
    αγγλικά: 'Lack of authorization to access this path',
    σουηδικά: 'Avsaknad av behörighet att komma åt den här sökvägen',
  },
  { ελληνικά: 'Έξοδος', αγγλικά: 'Logout', σουηδικά: 'Logga ut' },
  { ελληνικά: 'Ίσως', αγγλικά: 'Maybe', σουηδικά: 'Kanske' },
  { ελληνικά: 'Όλα', αγγλικά: 'All', σουηδικά: 'Allt' },
  { ελληνικά: 'Όνομα', αγγλικά: 'Name', σουηδικά: 'Namn' },
  { ελληνικά: 'Όχι', αγγλικά: 'No', σουηδικά: 'Nej' },
  // Α //
  { ελληνικά: 'Α -> Ω', αγγλικά: 'A -> Z', σουηδικά: 'A -> Ö' },
  { ελληνικά: 'Αιτήσεις', αγγλικά: 'Applications', σουηδικά: 'Applikationer' },
  { ελληνικά: 'Αλλαγή', αγγλικά: 'Edit', σουηδικά: 'Redigera' },
  { ελληνικά: 'Αλλαγή Γραφήματος', αγγλικά: 'Change Chart', σουηδικά: 'Ändra Diagram' },
  { ελληνικά: 'Ανάπτυξη Εφαρμογών', αγγλικά: 'Application Development', σουηδικά: 'Applikationsutveckling' },
  {
    ελληνικά: 'Αλλαγή εμφάνισης πλήκτρου δυναμικού υποβάθρου',
    αγγλικά: 'Add a List of "Course Projects" to an event',
    σουηδικά: 'Lägga till en lista över "Kursprojekt" till ett evenemang',
  },
  {
    ελληνικά: 'Αλλαγή χρώματος υποβάθρου του δυναμικού υποβάθρου',
    αγγλικά: 'Change background color of dynamic background',
    σουηδικά: 'Ändra bakgrundsfärgen för den dynamiska bakgrunden',
  },
  { ελληνικά: 'Ανάπτυξη Ιστού', αγγλικά: 'Web Development', σουηδικά: 'Webbutveckling' },
  { ελληνικά: 'Ανάπτυξη κώδικα φίλτρων', αγγλικά: 'Filter code development', σουηδικά: 'Utveckla filterkod' },
  { ελληνικά: 'Αναζήτηση', αγγλικά: 'Search', σουηδικά: 'Sök' },
  { ελληνικά: 'Παρατημένα', αγγλικά: 'Abandoned', σουηδικά: 'Övergiven' },
  { ελληνικά: 'Ανώτατο Εκπαιδευτικό Ίδρυμα', αγγλικά: 'Higher Educational Institution', σουηδικά: 'Högre Läroanstalt' },
  { ελληνικά: 'Αποθήκευση', αγγλικά: 'Submit', σουηδικά: 'Skicka In' },
  { ελληνικά: 'Αποθήκευση Αλλαγών', αγγλικά: 'Save Changes', σουηδικά: 'Spara Ändringar' },
  { ελληνικά: 'Αποκρινόμενος σχεδιασμός', αγγλικά: 'Responsive design', σουηδικά: 'Responsiv design' },
  { ελληνικά: 'Απομακρυσμένα', αγγλικά: 'Remotely', σουηδικά: 'Avlägset' },
  { ελληνικά: 'Απομακρυσμένη', αγγλικά: 'Remote', σουηδικά: 'Avlägsen' },
  { ελληνικά: 'Απορρίφθηκαν', αγγλικά: 'Rejected', σουηδικά: 'Avvisade' },
  { ελληνικά: 'Απορρίφθηκε', αγγλικά: 'Rejected', σουηδικά: 'Avvisade' },
  { ελληνικά: 'Αποστολή Μηνύματος', αγγλικά: 'Send Message', σουηδικά: 'Skicka Meddelande' },
  { ελληνικά: 'Αποτυχία Αυθεντικοποίησης', αγγλικά: 'Authentication Failure', σουηδικά: 'Misslyckad autentisering' },
  { ελληνικά: 'Αρ. Τηλεφώνου', αγγλικά: 'Ph. Number', σουηδικά: 'Telefonnummer' },
  { ελληνικά: 'Αριθμός Τηλεφώνου', αγγλικά: 'Phone Number', σουηδικά: 'Telefonnummer' },
  { ελληνικά: 'Αρχική Σελίδα', αγγλικά: 'Home Page', σουηδικά: 'Hemsida' },
  { ελληνικά: 'Αυτοκινητοβιομηχανία', αγγλικά: 'Automotive Industry', σουηδικά: 'Bilindustrin' },
  // Β //
  { ελληνικά: 'Βάση Δεδομένων', αγγλικά: 'Database', σουηδικά: 'Databas' },
  // Γ //
  { ελληνικά: 'για', αγγλικά: 'for', σουηδικά: 'för' },
  { ελληνικά: 'Γράφημα Περιοχής', αγγλικά: 'Area Chart', σουηδικά: 'Områdesdiagram' },
  { ελληνικά: 'Γράψτε το μήνυμά σας στα ελληνικά.', αγγλικά: 'Write your message in english.', σουηδικά: 'Skriv ditt meddelande på engelska.' },
  { ελληνικά: 'Γραφείο', αγγλικά: 'Office', σουηδικά: 'Kontor' },
  // Δ //
  { ελληνικά: 'Δεν βρέθηκαν εργασίες...', αγγλικά: 'No jobs found...', σουηδικά: 'Inga jobb hittades...' },
  { ελληνικά: 'Δεν είσαι μέλος; ', αγγλικά: 'Not a member? ', σουηδικά: 'Inte en medlem? ' },
  {
    ελληνικά: 'Δεν επιτρέπονται οι αλλαγές στην «Λειτουργία Επίδειξης».',
    αγγλικά: 'Changes are not allowed in «Demo Mode».',
    σουηδικά: 'Ändringar är inte tillåtna i «Demoläge».',
  },
  { ελληνικά: 'Δευτεροβάθμια Εκπαίδευση', αγγλικά: 'Secondary Education', σουηδικά: 'Gymnasieutbildning' },
  { 
    ελληνικά: 'Δημήτρης Μανωλόπουλος 2024 © Επιφύλαξη Παντός Δικαιώματος', 
    αγγλικά: 'Dimitris Manolopoulos 2024 © All Rights Reserved', 
    σουηδικά: 'Dimitris Manolopoulos 2024 © Med Ensamrätt',
  },
  { ελληνικά: 'Δημιουργία Λογότυπου', αγγλικά: 'Logo Creation', σουηδικά: 'Skapa En Logotyp' },
  { ελληνικά: 'Δημιουργία πλήκτρου μόνιμης εμφάνισης χρωμάτων', αγγλικά: 'Create a color permanent display button', σουηδικά: 'Skapa en permanent färgdisplaynyckel' },
  { ελληνικά: 'Διαγραφή', αγγλικά: 'Delete', σουηδικά: 'Radera' },
  { ελληνικά: 'Δοκιμής', αγγλικά: 'Test', σουηδικά: 'Testa' },
  { ελληνικά: 'Διαδικτυακή Βιβλιοθήκη Εκμάθησης', αγγλικά: 'Online Learning Library', σουηδικά: 'Online Lärande Bibliotek' },
  { ελληνικά: 'Δια ζώσης', αγγλικά: 'In person', σουηδικά: 'För livet' },
  { ελληνικά: 'Δυναμική', αγγλικά: 'Dynamic', σουηδικά: 'Dynamisk' },
  { ελληνικά: 'Δυναμικό', αγγλικά: 'Dynamic', σουηδικά: 'Dynamisk' },
  // Ε //
  { ελληνικά: 'ΕΠΙΣΤΡΟΦΗ', αγγλικά: 'RETURN', σουηδικά: 'LÄMNA TILLBAKA' },
  { ελληνικά: 'Είσαι ήδη μέλος; ', αγγλικά: 'Already a member? ', σουηδικά: 'Redan medlem? ' },
  { ελληνικά: 'Είσοδος', αγγλικά: 'Login', σουηδικά: 'Logga In' },
  { ελληνικά: 'Εγγράψου.', αγγλικά: 'Register.', σουηδικά: 'Registrera' },
  { ελληνικά: 'Εγγραφή', αγγλικά: 'Register', σουηδικά: 'Registrera' },
  { ελληνικά: 'Εγκρίθηκαν', αγγλικά: 'Approved', σουηδικά: 'Godkänd' },
  { ελληνικά: 'Εγκρίθηκε', αγγλικά: 'Approved', σουηδικά: 'Godkänd' },
  { ελληνικά: 'Εκκαθάριση', αγγλικά: 'Clear', σουηδικά: 'Klar' },
  { ελληνικά: 'Εκκρεμεί', αγγλικά: 'Pending', σουηδικά: 'I Väntan På' },
  { ελληνικά: 'Εκκρεμούν', αγγλικά: 'Pending', σουηδικά: 'I Väntan På' },
  { ελληνικά: 'Εν αναμονή', αγγλικά: 'Pending', σουηδικά: 'I Väntan På' },
  { ελληνικά: 'Ενεργοποίηση Φόρμας Επικοινωνίας', αγγλικά: 'Contact Form Activation', σουηδικά: 'Aktivering av Kontaktformulär' },
  { ελληνικά: 'Επίδειξη Εφαρμογής', αγγλικά: 'Application Demo', σουηδικά: 'Applikationsdemo' },
  { ελληνικά: 'Επεξεργασία Εργασίας', αγγλικά: 'Edit Job', σουηδικά: 'Redigera Jobb' },
  { ελληνικά: 'Επιδιόρθωση τρεμοπαίγματος σε safari', αγγλικά: 'Fix flickering in safari', σουηδικά: 'Åtgärda flimmer i safari' },
  { ελληνικά: 'Επικοινωνία', αγγλικά: 'Contact', σουηδικά: 'Kontakt' },
  { ελληνικά: 'Επιτυχής Έξοδος Χρήστη!', αγγλικά: 'User Logout Successful!', σουηδικά: 'Utloggning av användare lyckades!' },
  { ελληνικά: 'Επιτυχής Είσοδος! Ανακατεύθυνση...', αγγλικά: 'Login Successful! Redirect...', σουηδικά: 'Inloggningen lyckades! Dirigera om...' },
  { ελληνικά: 'Επιτυχής διαγραφή εργασίας!', αγγλικά: 'Job deleted successfully!', σουηδικά: 'Jobb raderades!' },
  { ελληνικά: 'Επόμενη', αγγλικά: 'Next', σουηδικά: 'Νästa' },
  { ελληνικά: 'Επιμονή κατάστασης', αγγλικά: 'State persistence', σουηδικά: 'Statlig uthållighet' },
  { ελληνικά: 'Επώνυμο', αγγλικά: 'Surname', σουηδικά: 'Efternamn' },
  { ελληνικά: 'Εργασία', αγγλικά: 'Job', σουηδικά: 'Jobb' },
  { ελληνικά: 'Εργασίες', αγγλικά: 'Jobs', σουηδικά: 'Jobb' },
  { ελληνικά: 'Εταιρεία', αγγλικά: 'Company', σουηδικά: 'Företag' },
  { ελληνικά: 'Εταιρεία Εκπαίδευσης Προγραμματιστών', αγγλικά: 'Developer Training Company', σουηδικά: 'Utbildningsföretag för Utvecklare' },
  // Ζ //
  // Η //
  { ελληνικά: 'Η Εργασία Ενημερώθηκε!', αγγλικά: 'Job Updated!', σουηδικά: 'Jobb uppdaterat!' },
  { ελληνικά: 'Η Εργασία Προστέθηκε!', αγγλικά: 'Job Added!', σουηδικά: 'Jobb tillagt!' },
  { ελληνικά: 'Η εργασία των ονείρων μου.', αγγλικά: 'My dream job.', σουηδικά: 'Mitt drömjobb.' },
  { ελληνικά: 'Η διαδρομή (route) δεν υπάρχει!', αγγλικά: 'The route does not exist!', σουηδικά: 'Rutten finns inte!' },
  { ελληνικά: 'Η πόλη μου', αγγλικά: 'My city', σουηδικά: 'Min stad' },
  { ελληνικά: 'Ηλεκτρονικό Ταχυδρομείο', αγγλικά: 'Electronic Mail', σουηδικά: 'Elektronisk Post' },
  { ελληνικά: 'Ηλ. Ταχυδρομείο', αγγλικά: 'E-Mail', σουηδικά: 'E-Post' },
  { ελληνικά: 'Ημιαπασχόληση', αγγλικά: 'Part-Time', σουηδικά: 'Deltid' },
  // Θ //
  { ελληνικά: 'Θέμα', αγγλικά: 'Subject', σουηδικά: 'Ämne' },
  { ελληνικά: 'Θέση Εργασίας', αγγλικά: 'Job Position', σουηδικά: 'Befattning' },
  { ελληνικά: 'Θετικών & Τεχνολογικών Επιστημών', αγγλικά: 'Sciences & Technology', σουηδικά: 'Positiva & Tekniska Vetenskaper' },
  // Ι //
  { ελληνικά: 'Ιστότοπο', αγγλικά: 'Website', σουηδικά: 'Webbplats' },
  // Κ //
  { 
    ελληνικά: 'Καθαρισμός & τακτοποίηση του κώδικα', 
    αγγλικά: 'Cleaning & tidying up the code', 
    σουηδικά: 'Rengöring och ordning av koden' 
  },
  { ελληνικά: 'Καθαρισμός Φίλτρων', αγγλικά: 'Clear Filters', σουηδικά: 'Rensa Filter' },
  { ελληνικά: 'Κατάσταση Αίτησης', αγγλικά: 'Application Status', σουηδικά: 'Ansökningsstatus' },
  { ελληνικά: 'Κενό', αγγλικά: 'Null', σουηδικά: 'Noll' },
  { ελληνικά: 'Κομμάτι', αγγλικά: 'Component', σουηδικά: 'Komponent' },
  { ελληνικά: 'Κολλέγιο DEI', αγγλικά: 'DEI College', σουηδικά: 'DEI College' },
  { ελληνικά: 'Κωδικός', αγγλικά: 'Password', σουηδικά: 'Lösenord' },
  // Λ //
  { ελληνικά: 'Λάθος στοιχεία.', αγγλικά: 'Wrong data.', σουηδικά: 'Fel data.' },
  { ελληνικά: 'Λειτουργία', αγγλικά: 'Function', σουηδικά: 'Funktion' },
  // Μ //
  { ελληνικά: 'Μαρτυρίες', αγγλικά: 'Testimonials', σουηδικά: 'Vittnesmål' },
  { ελληνικά: 'Μετάφραση', αγγλικά: 'Translation', σουηδικά: 'Översättning' },
  { ελληνικά: 'Μηνιαία Δεδομένα', αγγλικά: 'Monthly Data', σουηδικά: 'Månadsdata' },
  // Ν //
  { ελληνικά: 'Ναι', αγγλικά: 'Yes', σουηδικά: 'Ja' },
  { ελληνικά: 'Νεότερες', αγγλικά: 'Newest', σουηδικά: 'Nyaste' },
  // Ξ //
  // Ο //
  {
    ελληνικά: 'Ο Χρήστης Δημιουργήθηκε! Ανακατεύθυνση...',
    αγγλικά: 'User Created! Redirect...',
    σουηδικά: 'Användare skapad! Dirigera om...',
  },
  { ελληνικά: 'Οδηγός Ανάπτυξης Εφαρμογών iOS', αγγλικά: 'iOS Application Development Guide', σουηδικά: 'Utvecklingsguide för iOS-Appar' },
  { ελληνικά: 'Ολοκληρωμένα', αγγλικά: 'Completed', σουηδικά: 'Avslutad' },
  { ελληνικά: 'Οργάνωση', αγγλικά: 'Sort', σουηδικά: 'Sortera' },
  // Π //
  {
    ελληνικά:
      'Πάρα πολλά αιτήματα από αυτήν την διεύθυνση IP, δοκιμάστε ξανά μετά από 15 λεπτά.',
    αγγλικά:
      'Too many requests from this IP address, please try again in 15 minutes.',
    σουηδικά:
      'För många förfrågningar från denna IP-adress, försök igen om 15 minuter.',
  },
  { ελληνικά: 'Πίνακας', αγγλικά: 'Dashboard', σουηδικά: 'Instrumentbräda' },
  { ελληνικά: 'Παλαιότερες', αγγλικά: 'Oldest', σουηδικά: 'Äldst' },
  { ελληνικά: 'Πανεπιστήμιο Κρήτης', αγγλικά: 'University of Crete', σουηδικά: 'Universitetet på Kreta' },
  { ελληνικά: 'Πανεπιστήμιο του Πόρτσμουθ', αγγλικά: 'University of Portsmouth', σουηδικά: 'Universitetet på Portsmouth' },
  { ελληνικά: 'Παρακαλώ Περιμένετε...', αγγλικά: 'Please Wait...', σουηδικά: 'Vänta Snäll...' },
  { ελληνικά: 'Πλήρες Όνομα', αγγλικά: 'Full Name', σουηδικά: 'Fullständigt Namn' },
  { ελληνικά: 'Πλήρης Απασχόληση', αγγλικά: 'Full-Time', σουηδικά: 'Heltid' },
  { ελληνικά: 'Πλήρης Οδηγός React 2024', αγγλικά: 'Complete React 2024 Guide', σουηδικά: 'React 2024 Komplett Guide' },
  { ελληνικά: 'Πλήρους-Εύρους Ανάπτυξη Ιστού 2024', αγγλικά: 'Full-Stack Web Development 2024', σουηδικά: 'Full-Stack Webbutveckling 2024' },
  { ελληνικά: 'Πλήρους-Εύρους Javascript', αγγλικά: 'Full-Stack Javascript', σουηδικά: 'Full-Stack Javascript' },
  { ελληνικά: 'Πρακτική', αγγλικά: 'Internship', σουηδικά: 'Praktik' },
  { ελληνικά: 'Προγραμματιστής Πλήρους-Εύρους', αγγλικά: 'Full-Stack Developer', σουηδικά: 'Full-Stack Utvecklare' },
  { ελληνικά: 'Πρόγραμμα Εκκίνησης', αγγλικά: 'Bootcamp', σουηδικά: 'Bootcamp' },
  { ελληνικά: 'Προηγούμενη', αγγλικά: 'Previous ', σουηδικά: 'Tidigare' },
  { ελληνικά: 'Προς Υλοποίηση', αγγλικά: 'To Be Implemented', σουηδικά: 'För Implementering' },
  {
    ελληνικά: 'Προσθήκη επιλογών φίλτρου',
    αγγλικά: 'Add filter options',
    σουηδικά: 'Lägg till filteralternativ',
  },
  {
    ελληνικά: 'Προσθήκη Πλήκτρου για «Έργα Μαθήματος» σε γεγονός',
    αγγλικά: 'Add a Button for "Course Projects" to an event',
    σουηδικά: 'Lägga till en "Kursprojekt"-knapp till ett evenemang',
  },
  {
    ελληνικά: 'Προσθήκη Λίστας με «Έργα Μαθήματος» σε γεγονός',
    αγγλικά: 'Add a List of "Course Projects" to an event',
    σουηδικά: 'Lägga till en lista över "Kursprojekt" till ett evenemang',
  },
  {
    ελληνικά: 'Προσθήκη χρόνου διάρκειας γεγονότος',
    αγγλικά: 'Add event duration time',
    σουηδικά: 'Lägg till händelsens varaktighetstid',
  },
  { ελληνικά: 'Προσθήκη Εργασίας', αγγλικά: 'Add Job', σουηδικά: 'Lägg Τill Jobb' },
  { ελληνικά: 'Πρόσληψη', αγγλικά: 'Hire Me', σουηδικά: 'Αnställ Mig' },
  { ελληνικά: 'Προσωπικός Ιστότοπος', αγγλικά: 'Personal Website', σουηδικά: 'Personlig Webbplats' },
  // Ρ //
  { ελληνικά: 'Ραβδόγραμμα', αγγλικά: 'Bar Chart', σουηδικά: 'Stapeldiagram' },
  // Σ //
  { ελληνικά: 'Σειρά Μαθημάτων', αγγλικά: 'Course', σουηδικά: 'Kurs' },
  { ελληνικά: 'Σελίδα Χρήστη', αγγλικά: 'Profile', σουηδικά: 'Profil' },
  { ελληνικά: 'Σελίδα «Αρχική»', αγγλικά: 'Page "Home"', σουηδικά: 'Hemsida' },
  { ελληνικά: 'Σελίδα «Επικοινωνία»', αγγλικά: 'Page "Contact"', σουηδικά: 'Sidan "Kontakt"' },
  { ελληνικά: 'Σελίδα «Προς Υλοποίηση»', αγγλικά: 'Page "To Be Implemented"', σουηδικά: 'Sidan "För Implementering"' },
  { ελληνικά: 'Σελίδα «Χρονολόγιο»', αγγλικά: 'Page "Timeline"', σουηδικά: 'Sidan "Tidslinje"' },
  { ελληνικά: 'Σε εξέλιξη', αγγλικά: 'In progress', σουηδικά: 'In progress' },
  { ελληνικά: 'Σπουδές', αγγλικά: 'Studies', σουηδικά: 'Studier' },
  { ελληνικά: 'Σπουδές Προγραμματισμού', αγγλικά: 'Programming Studies', σουηδικά: 'Programmeringsstudier' },
  { ελληνικά: 'Στατικό', αγγλικά: 'Static', σουηδικά: 'Statisk' },
  { 
    ελληνικά: 'Στις δεύτερες Πανελλήνιες Εξετάσεις κατάφερα να περάσω στο Πολυτεχνείο του Πανεπιστημίου Κρήτης όπου όμως επίσης επέλεξα να μην πάω.', 
    αγγλικά: 'In the second Panhellenic Exams, I managed to pass the Technical University of Crete, but I also chose not to go.', 
    σουηδικά: 'I det andra panhelleniska provet lyckades jag gå vidare till yrkeshögskolan vid universitetet på Kreta, men jag valde också att inte gå.', 
  },
  { ελληνικά: 'Συμβουλευτική', αγγλικά: 'Consulting', σουηδικά: 'Konsultera' },
  {
    ελληνικά: 'Συμμετοχή σε τρίμηνο εντατικό πρόγραμμα εκκίνησης για εκπαίδευση επάνω σε τεχνολογίες ανάπτυξης ιστού για πλήρους-εύρους JavaScript.',
    αγγλικά: 'Participation in a three-month intensive bootcamp for training on web development technologies for full-stack JavaScript.',
    σουηδικά: 'Deltagande i en tre månader lång intensiv bootcamp för utbildning i webbutvecklingsteknologier för fullstack JavaScript.',
  },
  {
    ελληνικά: 'Συμπλήρωσε όλα τα πεδία!',
    αγγλικά: 'Fill in all fields!',
    σουηδικά: 'Fyll i alla fält!',
  },
  {
    ελληνικά: 'Συμπλήρωση γεγονότων Χρονολογίου',
    αγγλικά: 'Completing Timeline events',
    σουηδικά: 'Fylla i tidslinjehändelser',
  },
  { ελληνικά: 'Συνέντευξη', αγγλικά: 'Interview', σουηδικά: 'Intervju' },
  { ελληνικά: 'Συνδέσου.', αγγλικά: 'Login.', σουηδικά: 'Logga In' },
  { ελληνικά: 'Συνεργασία', αγγλικά: 'Cooperation', σουηδικά: 'Samarbete' },
  { ελληνικά: 'Σύνδεση', αγγλικά: 'Login', σουηδικά: 'Logga In' },
  { ελληνικά: 'Συχνές Ερωτήσεις', αγγλικά: 'FAQ', σουηδικά: 'Vanliga Frågor' },
  { ελληνικά: 'Σχετικά με εμένα', αγγλικά: 'About me', σουηδικά: 'Om mig' },
  // Τ //
  {
    ελληνικά: 'Τα Στοιχεία Χρήστη Ενημερώθηκαν!',
    αγγλικά: 'User Details Updated!',
    σουηδικά: 'Användarinformation uppdaterad!',
  },
  { ελληνικά: 'Τοποθεσία', αγγλικά: 'Location', σουηδικά: 'Spårande' },
  { ελληνικά: 'Τύπος Εργασίας', αγγλικά: 'Job Type', σουηδικά: 'Arbetstyp' },
  // Υ //
  { ελληνικά: 'Υβριδικά', αγγλικά: 'Hybrid', σουηδικά: 'Hybrid' },
  { ελληνικά: 'Υβριδική', αγγλικά: 'Hybrid', σουηδικά: 'Hybrid' },
  { ελληνικά: 'Υπηρεσίες', αγγλικά: 'Services', σουηδικά: 'Tjänster' },
  {
    ελληνικά: 'Υπήρξε κάποιο πρόβλημα. Δοκιμάστε ξανά σε λίγο.',
    αγγλικά: 'There was a problem. Please try again shortly.',
    σουηδικά: 'Det var ett problem. Försök snart igen.',
  },
  { ελληνικά: 'Υπό Ανάπτυξη', αγγλικά: 'Under Development', σουηδικά: 'Under Utveckling' },
  // Φ //
  { ελληνικά: 'Φίλτρα Αναζήτησης', αγγλικά: 'Search Filters', σουηδικά: 'Sökfilter' },
  {
    ελληνικά:
      'Φαίνεται ότι δεν μπορούμε να ξετρυπώσουμε την σελίδα που ψάχνεις.',
    αγγλικά:
      'It looks like we are not able to find the page you are looking for.',
    σουηδικά: 'Det verkar som att vi inte kan hitta sidan du letar efter.',
  },
  { ελληνικά: 'Φόρτωση', αγγλικά: 'Loading', σουηδικά: 'Laddning' },
  { ελληνικά: 'Φόρτωση...', αγγλικά: 'Loading...', σουηδικά: 'Laddning...' },
  // Χ //
  { ελληνικά: 'Χαρτοφυλάκιο', αγγλικά: 'Portfolio', σουηδικά: 'Portfölj' },
  { ελληνικά: 'Χρήστης', αγγλικά: 'User', σουηδικά: 'Användare' },
  { ελληνικά: 'Χρονική Γραμμή', αγγλικά: 'Timeline', σουηδικά: 'Tidslinje' },
  { ελληνικά: 'Χρονολόγιο', αγγλικά: 'Timeline', σουηδικά: 'Tidslinje' },
  // Ψ //
  // Ω //
  { ελληνικά: 'Ω -> Α', αγγλικά: 'Z -> A', σουηδικά: 'Ö -> A' },
  {
    ελληνικά: 'ΩΠ! ΚΑΤΙ ΠΗΓΕ ΛΑΘΟΣ.',
    αγγλικά: 'OOPS! SOMETHING WENT WRONG.',
    σουηδικά: 'HOPPSAN! NÅGOT GICK FEL.',
  },
  { ελληνικά: 'ηΤαχυδρομείο', αγγλικά: 'eMail', σουηδικά: 'ePost' },
  {
    ελληνικά: 'παράδειγμα@ταχυδρομείο.gr',
    αγγλικά: 'example@email.com',
    σουηδικά: 'exempel@e-post.com',
  },
  {
    ελληνικά: '5ήμερη Πρόκληση Προγραμματισμού',
    αγγλικά: '5-Day Programming Challenge',
    σουηδικά: '5-Dagars Programmeringsutmaning',
  },
  { ελληνικά: 'CSS', αγγλικά: 'CSS', σουηδικά: 'CSS' },
  { ελληνικά: 'CSS 2024', αγγλικά: 'CSS 2024', σουηδικά: 'CSS 2024' },
  { ελληνικά: 'HTML', αγγλικά: 'HTML', σουηδικά: 'HTML' },
  { ελληνικά: 'JavaScript', αγγλικά: 'JavaScript', σουηδικά: 'JavaScript' },
  { ελληνικά: 'MERN 2023', αγγλικά: 'MERN 2023', σουηδικά: 'MERN 2023' },
  { ελληνικά: 'React Native 2023', αγγλικά: 'React Native 2023', σουηδικά: 'React Native 2023' },
];
